-- sine_lut_pkg.vhd
-- Quarter-wave sine table, 10-bit phase x 10-bit amplitude.
-- AUTO-GENERATED by tools/gen_sine_lut.py - do not edit by hand.
--
--   LUT(i) = round((2**(AMPL_WIDTH-1) - 1) * sin(2*pi*i / 2**PHASE_WIDTH)),
--            i = 0 .. 2**(PHASE_WIDTH-2) - 1
--
-- Only ieee.numeric_std is used (no Synopsys std_logic_arith), so the package
-- is portable across VHDL-93 / VHDL-2008 simulators and synthesis tools.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package sine_lut_pkg is

  constant PHASE_WIDTH : positive := 10;
  constant AMPL_WIDTH  : positive := 10;

  -- the table stores one quarter of a period
  constant LUT_DEPTH : positive := 2**(PHASE_WIDTH-2);

  subtype ampl_word is std_logic_vector(AMPL_WIDTH-1 downto 0);
  type lut_type is array (0 to LUT_DEPTH-1) of ampl_word;

  -- helper: integer -> two's complement amplitude word
  function S(v : integer) return ampl_word;

end package sine_lut_pkg;

package body sine_lut_pkg is

  function S(v : integer) return ampl_word is
  begin
    return std_logic_vector(to_signed(v, AMPL_WIDTH));
  end function;

end package body sine_lut_pkg;

library ieee;
use ieee.std_logic_1164.all;
use work.sine_lut_pkg.all;

package sine_lut_data is

  constant sine_lut : lut_type := (
    S(  0), S(  3), S(  6), S(  9),
    S( 13), S( 16), S( 19), S( 22),
    S( 25), S( 28), S( 31), S( 34),
    S( 38), S( 41), S( 44), S( 47),
    S( 50), S( 53), S( 56), S( 59),
    S( 63), S( 66), S( 69), S( 72),
    S( 75), S( 78), S( 81), S( 84),
    S( 87), S( 90), S( 94), S( 97),
    S(100), S(103), S(106), S(109),
    S(112), S(115), S(118), S(121),
    S(124), S(127), S(130), S(133),
    S(136), S(139), S(142), S(145),
    S(148), S(151), S(154), S(157),
    S(160), S(163), S(166), S(169),
    S(172), S(175), S(178), S(181),
    S(184), S(187), S(190), S(193),
    S(196), S(198), S(201), S(204),
    S(207), S(210), S(213), S(216),
    S(218), S(221), S(224), S(227),
    S(230), S(233), S(235), S(238),
    S(241), S(244), S(246), S(249),
    S(252), S(255), S(257), S(260),
    S(263), S(265), S(268), S(271),
    S(273), S(276), S(279), S(281),
    S(284), S(286), S(289), S(292),
    S(294), S(297), S(299), S(302),
    S(304), S(307), S(309), S(312),
    S(314), S(317), S(319), S(322),
    S(324), S(327), S(329), S(331),
    S(334), S(336), S(338), S(341),
    S(343), S(345), S(348), S(350),
    S(352), S(355), S(357), S(359),
    S(361), S(364), S(366), S(368),
    S(370), S(372), S(374), S(377),
    S(379), S(381), S(383), S(385),
    S(387), S(389), S(391), S(393),
    S(395), S(397), S(399), S(401),
    S(403), S(405), S(407), S(409),
    S(410), S(412), S(414), S(416),
    S(418), S(420), S(421), S(423),
    S(425), S(427), S(428), S(430),
    S(432), S(433), S(435), S(437),
    S(438), S(440), S(441), S(443),
    S(445), S(446), S(448), S(449),
    S(451), S(452), S(454), S(455),
    S(456), S(458), S(459), S(461),
    S(462), S(463), S(465), S(466),
    S(467), S(468), S(470), S(471),
    S(472), S(473), S(474), S(476),
    S(477), S(478), S(479), S(480),
    S(481), S(482), S(483), S(484),
    S(485), S(486), S(487), S(488),
    S(489), S(490), S(491), S(492),
    S(492), S(493), S(494), S(495),
    S(496), S(496), S(497), S(498),
    S(499), S(499), S(500), S(501),
    S(501), S(502), S(502), S(503),
    S(503), S(504), S(505), S(505),
    S(505), S(506), S(506), S(507),
    S(507), S(508), S(508), S(508),
    S(509), S(509), S(509), S(509),
    S(510), S(510), S(510), S(510),
    S(510), S(511), S(511), S(511),
    S(511), S(511), S(511), S(511)
  );

end package sine_lut_data;
