#!/usr/bin/env python3
"""
gen_sine_lut.py - generate the quarter-wave sine look-up-table package.

Replaces the original MATLAB script (matlab/sine_lut_gen.m, not included in the
course hand-out). The table holds the first quarter of a sine period:

    LUT[i] = round( (2^(A-1) - 1) * sin(2*pi*i / 2^P) ),   i = 0 .. 2^(P-2) - 1

with P = phase width and A = amplitude width. Values are signed but always
non-negative, so the MSB of every entry is 0 (synthesis removes that flop).

The script can also verify an existing package against the formula, which is
how we confirmed that the hand-out's sine_lut_10_x_10.vhd is exactly
round(511*sin(.)) for all 256 entries.

Usage
  python3 tools/gen_sine_lut.py --phase 10 --ampl 10 -o rtl/sine_lut_pkg.vhd
  python3 tools/gen_sine_lut.py --check rtl/original/sine_lut_10_x_10.vhd
  python3 tools/gen_sine_lut.py --phase 10 --ampl 10 --json docs/data/lut.json
"""
import argparse
import json
import math
import re
import sys


def table(phase_width: int, ampl_width: int):
    amp = 2 ** (ampl_width - 1) - 1
    n = 2 ** (phase_width - 2)
    return [round(amp * math.sin(2 * math.pi * i / 2 ** phase_width)) for i in range(n)]


def full_wave(phase_width: int, ampl_width: int):
    amp = 2 ** (ampl_width - 1) - 1
    return [round(amp * math.sin(2 * math.pi * i / 2 ** phase_width)) for i in range(2 ** phase_width)]


def vhdl(phase_width: int, ampl_width: int) -> str:
    t = table(phase_width, ampl_width)
    w = len(str(max(t)))
    rows = []
    for i in range(0, len(t), 4):
        rows.append("    " + ", ".join(f"S({v:{w}d})" for v in t[i:i + 4]))
    body = ",\n".join(rows)
    return f"""-- sine_lut_pkg.vhd
-- Quarter-wave sine table, {phase_width}-bit phase x {ampl_width}-bit amplitude.
-- AUTO-GENERATED by tools/gen_sine_lut.py - do not edit by hand.
--
--   LUT(i) = round((2**(AMPL_WIDTH-1) - 1) * sin(2*pi*i / 2**PHASE_WIDTH)),
--            i = 0 .. 2**(PHASE_WIDTH-2) - 1
--
-- Only ieee.numeric_std is used (no Synopsys std_logic_arith), so the package
-- is portable across VHDL-93 / VHDL-2008 simulators and synthesis tools.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package sine_lut_pkg is

  constant PHASE_WIDTH : positive := {phase_width};
  constant AMPL_WIDTH  : positive := {ampl_width};

  -- the table stores one quarter of a period
  constant LUT_DEPTH : positive := 2**(PHASE_WIDTH-2);

  subtype ampl_word is std_logic_vector(AMPL_WIDTH-1 downto 0);
  type lut_type is array (0 to LUT_DEPTH-1) of ampl_word;

  -- helper: integer -> two's complement amplitude word
  function S(v : integer) return ampl_word;

end package sine_lut_pkg;

package body sine_lut_pkg is

  function S(v : integer) return ampl_word is
  begin
    return std_logic_vector(to_signed(v, AMPL_WIDTH));
  end function;

end package body sine_lut_pkg;

library ieee;
use ieee.std_logic_1164.all;
use work.sine_lut_pkg.all;

package sine_lut_data is

  constant sine_lut : lut_type := (
{body}
  );

end package sine_lut_data;
"""


def vhdl_full(phase_width: int, ampl_width: int) -> str:
    """Full-period table used as an *independent specification* by the property
    monitor: it is computed straight from sin(), with no quadrant folding."""
    t = full_wave(phase_width, ampl_width)
    rows = []
    for i in range(0, len(t), 8):
        rows.append("    " + ", ".join(f"{v:4d}" for v in t[i:i + 8]))
    body = ",\n".join(rows)
    return f"""-- sine_full_pkg.vhd - full-period sine reference for the formal properties.
-- AUTO-GENERATED by tools/gen_sine_lut.py --full - do not edit by hand.
-- SINE_FULL(p) = round({2**(ampl_width-1)-1} * sin(2*pi*p/{2**phase_width})), p = 0 .. {2**phase_width - 1}

package sine_full_pkg is
  type full_table is array (0 to {2**phase_width - 1}) of integer range {-(2**(ampl_width-1))} to {2**(ampl_width-1)-1};
  constant SINE_FULL : full_table := (
{body}
  );
end package sine_full_pkg;
"""


def check(path: str) -> int:
    txt = open(path).read()
    pw = int(re.search(r"PHASE_WIDTH\s*:\s*\w+\s*:=\s*(\d+)", txt).group(1))
    aw = int(re.search(r"AMPL_WIDTH\s*:\s*\w+\s*:=\s*(\d+)", txt).group(1))
    vals = [int(x) for x in re.findall(r"conv_std_logic_vector\((-?\d+),\s*AMPL_WIDTH\)", txt)]
    ref = table(pw, aw)
    bad = [(i, a, b) for i, (a, b) in enumerate(zip(vals, ref)) if a != b]
    print(f"{path}: {len(vals)} entries, phase {pw} bit, amplitude {aw} bit, "
          f"{'matches' if not bad and len(vals) == len(ref) else 'DIFFERS FROM'} round({2**(aw-1)-1}*sin())")
    for i, a, b in bad[:10]:
        print(f"  entry {i}: file {a}, formula {b}")
    return 0 if not bad and len(vals) == len(ref) else 1


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--phase", type=int, default=10)
    ap.add_argument("--ampl", type=int, default=10)
    ap.add_argument("-o", "--output")
    ap.add_argument("--json")
    ap.add_argument("--check")
    ap.add_argument("--full", help="write the full-period reference package (formal properties)")
    a = ap.parse_args()
    if a.check:
        sys.exit(check(a.check))
    if a.phase < 3 or a.ampl < 2:
        sys.exit("phase width must be >= 3 and amplitude width >= 2")
    if a.output:
        open(a.output, "w").write(vhdl(a.phase, a.ampl))
    if a.full:
        open(a.full, "w").write(vhdl_full(a.phase, a.ampl))
    if a.json:
        json.dump({"phase_width": a.phase, "ampl_width": a.ampl, "quarter": table(a.phase, a.ampl),
                   "full": full_wave(a.phase, a.ampl)}, open(a.json, "w"))
    if not (a.output or a.json or a.full):
        sys.stdout.write(vhdl(a.phase, a.ampl))


if __name__ == "__main__":
    main()
